name: Comment on stale discussions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      discussions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@32110d4e311bd8996b2a82bf2a43b714ccc91777

      - name: Bundle install
        run: bundle install

      - name: Comment on discussions
        run: .github/actions/comment
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
