name: Comment on stale discussions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      discussions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@d781c1b4ed31764801bfae177617bb0446f5ef8d

      - name: Bundle install
        run: bundle install

      - name: Comment on discussions
        run: .github/actions/comment
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
